adminUser:
  password: vault:dineshmistry/adminUser:password
  username: admin
enableDocker: false
pipelineUser:
  email: dmistry+roboto@trustyourinbox.com
  token: vault:dineshmistry/pipelineUser:token
  username: TrustYourInboxRoboto
prow:
  hmacToken: vault:dineshmistry/prow:hmacToken
